package bd.kpay.agent;
import android.Manifest;
import android.app.*;
import android.content.*;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.*;
import android.telephony.SubscriptionInfo;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.text.DateFormat;
import java.util.*;
import java.util.concurrent.*;

public class MainActivity extends Activity {
 private LinearLayout content;private String screen="Home";private final ExecutorService worker=Executors.newSingleThreadExecutor();private final Handler handler=new Handler(Looper.getMainLooper());private boolean busy;
 private final Runnable refresh=new Runnable(){public void run(){try{if(!busy&&screen.equals("Home")&&!Vault.get(MainActivity.this,"key").isEmpty())render();}catch(Exception ignored){}handler.postDelayed(this,5000);}};
 private static final int GREEN=0xff176b54,INK=0xff172c27,MUTED=0xff64746e;
 public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(0xfff4f7f5);getWindow().setNavigationBarColor(Color.WHITE);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);SyncJob.schedule(this,false);render();}
 public void onResume(){super.onResume();handler.postDelayed(refresh,5000);}
 public void onPause(){handler.removeCallbacks(refresh);super.onPause();}
 public void onDestroy(){worker.shutdown();super.onDestroy();}
 int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
 LinearLayout column(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}
 TextView text(String s,int size,int color,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);t.setPadding(0,dp(5),0,dp(5));return t;}
 GradientDrawable bg(int color){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(16));return d;}
 LinearLayout card(String title){LinearLayout box=column();box.setPadding(dp(18),dp(14),dp(18),dp(14));box.setBackground(bg(Color.WHITE));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(14);content.addView(box,p);box.addView(text(title,17,INK,true));return box;}
 void detail(LinearLayout l,String name,String value){l.addView(text(name.toUpperCase(Locale.ROOT),11,MUTED,true));l.addView(text(value,15,INK,false));}
 void button(LinearLayout l,String label,Runnable action){Button b=new Button(this);b.setText(label);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setBackgroundTintList(android.content.res.ColorStateList.valueOf(GREEN));b.setEnabled(!busy);l.addView(b,new LinearLayout.LayoutParams(-1,dp(50)));b.setOnClickListener(v->action.run());}
 String date(long time){return time==0?"Not yet":DateFormat.getDateTimeInstance(DateFormat.SHORT,DateFormat.SHORT).format(new Date(time));}
 void render(){
  LinearLayout root=column();root.setBackgroundColor(0xfff4f7f5);root.setPadding(dp(18),dp(14),dp(18),dp(10));root.setOnApplyWindowInsetsListener((view,insets)->{view.setPadding(dp(18),dp(14)+insets.getSystemWindowInsetTop(),dp(18),dp(10)+insets.getSystemWindowInsetBottom());return insets;});setContentView(root);
  root.addView(text("kPay / AGENT",14,GREEN,true));root.addView(text(screen.equals("Home")?"Collection overview":screen,28,INK,true));root.addView(text("Central accounts · secure SMS sync",13,MUTED,false));
  ScrollView scroll=new ScrollView(this);content=column();content.setPadding(0,dp(18),0,dp(10));scroll.addView(content);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
  try{if(Vault.get(this,"key").isEmpty())pairing();else switch(screen){case "Receipts":receipts(false);break;case "Queue":receipts(true);break;case "Accounts":accounts();break;case "Health":health();break;case "Settings":settings();break;default:home();}}
  catch(Exception e){card("Setup needs attention").addView(text("Encrypted device data is unavailable. Preserve pending receipts and contact your administrator before reinstalling.",14,INK,false));}
  HorizontalScrollView nav=new HorizontalScrollView(this);LinearLayout items=new LinearLayout(this);for(String s:new String[]{"Home","Receipts","Queue","Accounts","Health","Settings"}){Button b=new Button(this);b.setText(s);b.setTextSize(12);b.setAllCaps(false);b.setTextColor(screen.equals(s)?GREEN:MUTED);items.addView(b);b.setOnClickListener(v->{screen=s;render();});}nav.addView(items);root.addView(nav);
 }
 void pairing(){LinearLayout box=card("Connect this collection phone");box.addView(text("Enter the one-use code from Admin → Agent devices. The administrator assigns your receiving account and approves the physical SIM.",14,MUTED,false));detail(box,"Trusted server",BuildConfig.SERVER+(BuildConfig.DEBUG?" · development build":""));EditText code=new EditText(this);code.setHint("Pairing code");code.setSingleLine(true);code.setInputType(android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS);box.addView(code);button(box,"Pair device",()->{String value=code.getText().toString().trim();if(value.isEmpty()){toast("Enter a pairing code");return;}run(()->Api.enroll(this,value),"Phone paired. Grant permissions and select the collection SIM.");});}
 void home() throws Exception {JSONObject cfg=Device.config(this);boolean paused=getSharedPreferences("settings",0).getBoolean("paused",false);LinearLayout status=card(paused?"Capture paused":cfg.optString("status","Awaiting first sync").toUpperCase(Locale.ROOT));status.addView(text("Payment verification happens on the server after matching sender, transaction ID and exact amount.",14,MUTED,false));try(Queue q=new Queue(this)){detail(status,"Waiting / attention",q.depth()+" receipts");}detail(status,"Last successful sync",date(getSharedPreferences("health",0).getLong("last_sync",0)));String error=getSharedPreferences("health",0).getString("error","");if(!error.isEmpty())status.addView(text(error,14,0xffa46319,false));button(status,busy?"Syncing…":"Sync now",()->sync());LinearLayout next=card("Collection readiness");detail(next,"SMS permission",Device.permitted(this)?"Granted":"Required");detail(next,"Physical SIM",Device.healthy(this)?"Subscription "+Device.selected(this):"Select an active SIM");detail(next,"Admin binding",cfg.isNull("approved_subscription")?"Awaiting approval":"Subscription "+cfg.optInt("approved_subscription",-1));button(next,"Set up phone permissions & SIM",()->{screen="Health";render();});}
 void accounts() throws Exception {JSONObject cfg=Device.config(this),a=cfg.optJSONObject("account");LinearLayout box=card("Assigned receiving account");if(a==null){box.addView(text("Sync once to download your central assignment.",14,MUTED,false));return;}detail(box,"Provider / type",a.optString("provider").toUpperCase(Locale.ROOT)+" · "+a.optString("type"));detail(box,"Receiving number",a.optString("number"));detail(box,"SIM label",a.optString("sim"));detail(box,"Account status",a.optString("status"));detail(box,"Accepted SMS senders",cfg.optJSONArray("sms_senders")==null?"No published template":cfg.getJSONArray("sms_senders").join(", "));box.addView(text("Accounts and SMS formats are managed centrally. This phone cannot change payment numbers or verification rules.",14,MUTED,false));}
 void receipts(boolean onlyQueue) throws Exception {List<JSONObject> rows;try(Queue q=new Queue(this)){rows=q.list(false);}int count=0;for(JSONObject r:rows){String state=r.getString("state");if(onlyQueue&&state.equals("uploaded"))continue;count++;LinearLayout box=card(r.getString("origin")+" · "+state);detail(box,"Captured",date(r.getLong("captured")));detail(box,"Event ID",r.getString("id"));detail(box,"Attempts",Integer.toString(r.getInt("attempts")));if(!r.optString("result").isEmpty())detail(box,"Sync result",r.getString("result"));if(state.equals("quarantined"))box.addView(text("Subscription could not be trusted. This receipt is preserved locally and will not upload automatically.",14,0xffa46319,false));}if(count==0)card("No receipts yet").addView(text("Eligible provider SMS will appear here. Unrelated messages and OTPs are excluded.",14,MUTED,false));if(onlyQueue)button(card("Retry connection"),"Retry queued receipts",()->{try(Queue q=new Queue(this)){q.retry();}sync();});}
 void health(){LinearLayout box=card("Phone permissions");box.addView(text("kPay reads only newly received SMS from the admin’s provider allowlist and uploads payment evidence to the assigned server. OTPs and unrelated messages are excluded. Raw evidence is encrypted locally. Phone permission identifies active SIM subscriptions. No inbox history is read.",14,INK,false));detail(box,"SMS permission",Device.permitted(this)?"Granted":"Missing");button(box,"Review disclosure & grant permissions",()->new AlertDialog.Builder(this).setTitle("Allow payment SMS capture?").setMessage("This collection phone will capture newly received provider payment messages, retain encrypted evidence, and upload sender/message/SIM metadata to "+BuildConfig.SERVER+" for payment verification. Only approved provider senders are eligible; OTPs are excluded. You can pause capture in Settings.").setNegativeButton("Cancel",null).setPositiveButton("Continue",(d,w)->requestPermissions(new String[]{Manifest.permission.RECEIVE_SMS,Manifest.permission.READ_PHONE_STATE},10)).show());LinearLayout sims=card("Physical collection SIM");List<SubscriptionInfo> list=Device.sims(this);if(list.isEmpty())sims.addView(text("Grant phone permission and insert the collection SIM. SIM numbers are not inferred.",14,MUTED,false));for(SubscriptionInfo s:list){String label="SIM slot "+(s.getSimSlotIndex()+1)+" · "+s.getCarrierName()+" · subscription "+s.getSubscriptionId();button(sims,(s.getSubscriptionId()==Device.selected(this)?"✓ ":"")+label,()->new AlertDialog.Builder(this).setTitle("Confirm physical SIM").setMessage("Verify this slot contains the central receiving SIM. Changing subscription pauses approval on the server. Pending receipts remain preserved.").setNegativeButton("Cancel",null).setPositiveButton("Select",(d,w)->{getSharedPreferences("settings",0).edit().putInt("subscription",s.getSubscriptionId()).commit();sync();}).show());}LinearLayout diagnostics=card("Device health");detail(diagnostics,"Last capture",date(getSharedPreferences("health",0).getLong("last_capture",0)));detail(diagnostics,"Last sync",date(getSharedPreferences("health",0).getLong("last_sync",0)));detail(diagnostics,"SIM binding",Device.healthy(this)?"Selected subscription present":"Missing or unselected");detail(diagnostics,"Capture error",getSharedPreferences("health",0).getString("capture_error","None"));diagnostics.addView(text("Background sync is best effort. Keep this phone powered on, with mobile service and internet. Force-stopping the app blocks delivery until it is reopened.",14,MUTED,false));button(diagnostics,"Open Android app settings",()->startActivity(new Intent(android.provider.Settings.ACTION_APPLICATION_DETAILS_SETTINGS,android.net.Uri.parse("package:"+getPackageName()))));}
 void settings() throws Exception {LinearLayout box=card("Capture controls");boolean paused=getSharedPreferences("settings",0).getBoolean("paused",false);detail(box,"Device ID",Vault.get(this,"device_id"));detail(box,"Trusted server",BuildConfig.SERVER);detail(box,"Build","1.0 · "+(BuildConfig.DEBUG?"development":"release"));button(box,paused?"Resume SMS capture":"Pause SMS capture",()->{getSharedPreferences("settings",0).edit().putBoolean("paused",!paused).commit();render();});box.addView(text("Pausing stops new local capture. Already queued evidence still syncs. Uploaded means evidence was received, not that a payment was approved.",14,MUTED,false));button(box,"Re-pair with administrator",()->new AlertDialog.Builder(this).setTitle("Preserve pending receipts").setMessage("Re-pairing requires the same centrally assigned account. Queued receipts remain encrypted on this phone; never uninstall to fix a connection error.").setNegativeButton("Cancel",null).setPositiveButton("Enter new code",(d,w)->{try{Vault.save(this,"key","");Vault.save(this,"config","");render();}catch(Exception e){toast("Could not update encrypted credentials");}}).show());}
 interface Task {void execute() throws Exception;}
 void run(Task task,String success){if(busy)return;busy=true;worker.execute(()->{String message=success;try{task.execute();}catch(Exception e){message=e.getMessage()==null?"Operation failed":e.getMessage();}String result=message;runOnUiThread(()->{busy=false;toast(result);render();});});}
 void sync(){run(()->{SyncJob.sync(this);SyncJob.schedule(this,true);},"Sync check completed");}
 void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
 public void onRequestPermissionsResult(int n,String[] p,int[] r){super.onRequestPermissionsResult(n,p,r);render();}
}
